### ISSUE TITLE
Failed to sync with the API server  Please verify that your computer clock is correct, gives error in ChainStore.js file

### ISSUE THREAD

**Issue by M-Zeeshan-Haider** [bitshares/bitsharesjs#38] opened 2019-01-09 14:04 UTC
I am having error when in `ChanStore.js` file when i try to connect my own Witness node to the wallet by runing following command

`./programs/witness_node/witness_node --rpc-endpoint="0.0.0.0:8090"`

it gives following error , but it shows latency which means my Wallet is connected to Node but clock issue is there:

![screenshclockot](https://user-images.githubusercontent.com/36418814/50903304-57b72580-1415-11e9-8467-35ee9783bfef.png)

and this is the error i am able to see in ChainStore.js file  as follows:

![screenshot from 2019-01-09 13-51-28](https://user-images.githubusercontent.com/36418814/50903427-afee2780-1415-11e9-80d6-ff9e810997b3.png)

**Note**: i want to connect my own node to wallet, not anyothers nodes.
i have to connect only my specific node only.

**Comment by abitmore** [comment] 2019-01-09 17:35
Duplicate of #35. Close it?

**Closed** 2019-03-07 12:10 UTC
